---
name: Lint Annotations
description: Add or remove problem matchers for common linters
inputs:
  problem_matchers:
    description: Space-separated list of problem matchers to select (without .json file extension)
    required: false
    default: "*"
  enable:
    description: Whether to add or remove problem matchers
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - run: |
        if [ "${{ inputs.problem_matchers }}" = "*" ]; then
            matchers="$(find "${GITHUB_ACTION_PATH}/matchers/" -name "*.json" -exec basename {} .json \;)"
        else
            matchers="${{ inputs.problem_matchers }}"
        fi

        for matcher in ${matchers}; do
            if [ "${{ inputs.enable }}" = "true" ]; then
                path="${GITHUB_ACTION_PATH}/matchers/${matcher}.json"
                echo "Adding problem matcher ${path}"
                echo "::add-matcher::${path}"
            else
                echo "Removing problem matcher ${matcher}"
                echo "::remove-matcher owner=${matcher}::"
            fi
        done
      shell: bash
