---
name: Lint Annotations
description: Add or remove problem matchers for common linters
inputs:
  problem_matchers:
    description: Space-separated list of problem matchers to select (without .json file extension)
    required: false
    default: "*"
  enable:
    description: Whether to add or remove problem matchers
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        PROBLEM_MATCHERS: "${{ inputs.problem_matchers }}"
        ENABLE_PROBLEM_MATCHERS: "${{ inputs.enable }}"
