---
name: Keep version tags up-to-date

on:
  release:
    types:
      - published
      - edited

jobs:
  versioning:
    name: Update version tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - uses: Actions-R-Us/actions-tagger@v2.0.2
        with:
          publish_latest_tag: true
